project:
  type: website
  output-dir: docs

website:
  title: "Lily McMullen"
  navbar:
   background: primary
   left:
     - href: index.qmd
       text: Home
     - about.qmd
     - projects.qmd

format:
  html:
    theme: lux
    css: styles.css

editor: visual