project:
  type: website
  output-dir: docs

website:
  title: "home"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: minty
    css: styles.css

editor: visual

