project:
  type: website
  output-dir: docs

website:
  title: "Lily McMullen"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - Portfolio.qmd
      - href: resume.pdf
        text: Resume
      - about.qmd
      


format:
  html:
    theme: 
      - lux
    mainfont: Nunito
    toc: true

editor: visual