---
title: "About Me"
---

***Learn About Lily!***

I grew up in Portland, Oregon and quickly developed a love for nature and the outdoors at a young age. Since I was in middle school, I knew that my future career would have to do with taking care of the planet. I was lucky enough to have access to lots of camping trips, outdoor school, and the chance to interact with lots of plants and animals as a child, with hobbies like gardening and horseback riding.\

During my final year of high school, I attended Portland Community College as a dual-enrollment student. During this time, I was able to explore my interests in Computer Science and coding that I developed while I was in quarantine through the COVID-19 pandemic. I also began to take music more seriously, and started saving money to buy equipment for performing. I took advantage of my elective courses at PCC to learn how to code, and to learn more about ecology and how our environment works.\

In Fall of 2022, I moved across the country to a foreign state with only a car full of my things. I drove from Portland, Oregon to Tucson, Arizona to begin my studies at the U of A. I decided to pursue a major in Natural Resources, focusing on Conservation Biology, as well as a minor in Computer Science and a certificate in GIS. Since then, I have been chasing many opportunities the school has made availiable for me, while falling in love with the Sonoran desert and finding new places to share my songs.\

Thank you for taking the time to learn more about me!
---
